name: Compilazione PDF

on: [push, pull_request]

jobs:
  build_Latex:
    name: Build Latex
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Installazione dipendenze Latex
        run: |
          sudo apt-get update -y
          sudo apt-get install texlive-latex-recommended texlive-latex-extra
          sudo apt-get install -y latexmk
          sudo apt-get install -y texlive-lang-italian
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1

      - name: Compilazione Analisi dei Requisiti
        run: latexmk -pdf -cd DocumentazioneEsterna/AnalisiDeiRequisiti/AnalisiDeiRequisiti.tex

      - name: Compilazione Glossario
        run: |
          python DocumentazioneEsterna/Glossario/buildGlossarioForActions.py
          latexmk -pdf -cd DocumentazioneEsterna/Glossario/Glossario.tex
      
      - name: Compilazione Piano di Progetto
        run: latexmk -pdf -cd DocumentazioneEsterna/PianoDiProgetto/PianoDiProgetto.tex

      - name: Compilazione Piano di Qualififca
        run: latexmk -pdf -cd DocumentazioneEsterna/PianoDiQualifica/PianoDiQualifica.tex
      
      - name: Compilazione VerbaleX
        run: latexmk -pdf -cd DocumentazioneEsterna/VerbaliEsterni/VerbaleX/VerbaleX.tex

      - name: Compilazione Norme di Progetto
        run: latexmk -pdf -cd DocumentazioneInterna/NormeDiProgetto/NormeDiProgetto.tex

      - name: Compilazione Studio di Fattibilità
        run: latexmk -pdf -cd DocumentazioneInterna/StudioDiFattibilita/StudioDiFattibilita.tex

      - name: Compilazione VI_2020-11-23
        run: latexmk -pdf -cd DocumentazioneInterna/VerbaliInterni/VI_2020-11-23/VI_2020-11-23.tex

      - name: Compilazione VI_2020-12-02
        run: latexmk -pdf -cd DocumentazioneInterna/VerbaliInterni/VI_2020-12-02/VI_2020-12-02.tex

      - name: Compilazione Verbale interno 2020-11-16
        run: latexmk -pdf -cd DocumentazioneInterna/VerbaliInterni/VI_2020-11-16/VI_2020-11-16.tex

     
      - name: Creazione delle cartelle
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'develop' || github.event.pull_request.base.ref == 'main'
        run: |
          mkdir -p Documenti/DocumentazioneInterna/VerbaliInterni
          mkdir -p Documenti/DocumentazioneEsterna/VerbaliEsterni
          mkdir -p Documenti/LetterePresentazioni
          mv AnalisiDeiRequisiti.pdf Documenti/DocumentazioneEsterna
          mv Glossario.pdf Documenti/DocumentazioneEsterna
          mv PianoDiProgetto.pdf Documenti/DocumentazioneEsterna
          mv PianoDiQualifica.pdf Documenti/DocumentazioneEsterna
          mv VerbaleX.pdf Documenti/DocumentazioneEsterna/VerbaliEsterni
          mv NormeDiProgetto.pdf Documenti/DocumentazioneInterna
          mv StudioDiFattibilita.pdf Documenti/DocumentazioneInterna
          mv VI_2020-11-23.pdf Documenti/DocumentazioneInterna/VerbaliInterni
          mv VI_2020-12-02.pdf Documenti/DocumentazioneInterna/VerbaliInterni
          mv VI_2020-11-16.pdf Documenti/DocumentazioneInterna/VerbaliInterni

      
      - name: Upload Documenti
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'develop' || github.event.pull_request.base.ref == 'main'
        uses: actions/upload-artifact@v2
        with:
          name: Documentazione
          path: Documenti
          retention-days: 30

